# Generated by Django 5.2.4 on 2025-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('pop', models.IntegerField(default=0)),
                ('gentilic', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
