# Generated by Django 5.2.4 on 2025-07-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsky_cidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='pop',
            new_name='population',
        ),
    ]
