# Generated by Django 5.2.4 on 2025-07-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsky_cidades', '0002_rename_pop_city_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='population',
            new_name='est_pop',
        ),
        migrations.AddField(
            model_name='city',
            name='cns_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
